# Generated by Django 6.1.1 on 2026-10-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.IntegerField()),
                ('price', models.DecimalField(db_index=True, decimal_places=4, max_digits=7)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lng'], name='myapp_fuels_lat_e6f182_idx')],
            },
        ),
    ]
